# Thanks for downloading Shop! #
#==============================#

# If you want to use permissions with Shop, you must set this to true #
usePermissions: false


# =================================================================== #
#                      ECONOMY AND CURRENCY                           #
# =================================================================== #

# If you want to use virtual money, install the plugin Vault and set this to true #
# Otherwise, shops will use physical items as the economy on the server #
useVault: false

# If useVault is set to true, this is the currency symbol that is displayed #
vaultCurrencySymbol: $
# If useVault is set to false, this is the name name that is displayed #
# TO CHANGE THE ACTUAL ITEM THAT IS USED, RUN THE COMMAND '/SHOP CURRENCY' IN-GAME #
itemCurrencyName: Emerald(s)

# These allow you to charge money to players for creating/destroying their shops #
creationCost: 0
destructionCost: 0


# =================================================================== #
#                         GENERAL SETTINGS                            #
# =================================================================== #


# This will change the types of displays that shops will use above their chests #
# The options are: NONE, ITEM, GLASS_CASE, LARGE_ITEM #
displayType: ITEM

# This will make it so shops will only complete transactions if the item durabilities are the same #
checkItemDurability: true

# These will play sounds and particle effects when creating and using shops #
# These will need to be set to false if your server is running anything less than Minecraft 1.9 #
playSounds: true
playEffects: true

# This controls whether or not ender chests are able to be used as shops on the server #
enableEnderChests: false

# Add the names of worlds that you do not want shops to be able to be created in here #
worldBlacklist:
   example_world: true
   example2_world: true