# Thanks for downloading Shop! #
#==============================#

# If you want to use permissions with Shop, you must set this to true #
usePermissions: false

# If you want to use virtual money, install the plugin Vault and set this to true #
# Otherwise, shops will use physical items as the economy on the server #
useVault: false

# This will change the types of displays that shops will use above their chests #
# The options are: NONE, ITEM, LARGE_ITEM #
displayType: ITEM

# This will make it so shops will only complete transactions if the item durabilities are the same #
checkItemDurability: true

# These will play sounds and particle effects when creating and using shops #
# These will need to be set to false if your server is running anything less than Minecraft 1.9 #
playSounds: true
playEffects: true



# THIS SECTION IS ONLY USED IF VAULT IS BEING USED ON THE SERVER #
# ================================================================== #

# This will be the symbol in front of your currency on shop signs #
# For example, if your server is using 'cents' you would use the cents symbol #
vaultCurrencySymbol: $
# ================================================================== #



# THIS SECTION IS ONLY USED IF VAULT IS NOT BEING USED ON THE SERVER #
# ================================================================== #

# For item IDs, use this website:  http://minecraft-ids.grahamedgecombe.com  #
# For example, if you wanted to use Lapis Lazuli as your currency, put 351;4    #
# Default is set to Emerald (388;0) #
itemCurrencyID: 388;0

# This is what your currency will be called on shop signs #
# This should match the name of the item you are using for the section above #
itemCurrencyName: Emerald(s)
# ================================================================== #


# This controls whether or not ender chests are able to be used as shops on the server #
enableEnderChests: true

# These allow you to charge money to players for creating/destroying their shops #
creationCost: 0
destructionCost: 0


# Add the names of worlds that you do not want shops to be able to be created in here #
worldBlacklist:
   example_world: true
   example2_world: true