# THIS FILE IS USED TO CONFIGURE WHAT MESSAGES ARE DISPLAYED #
# ================================================================== #
# &b : AQUA
# &0 : BLACK
# &9 : BLUE
# &l : BOLD
# &3 : DARK_AQUA
# &1 : DARK_BLUE
# &8 : DARK_GRAY
# &2 : DARK_GREEN
# &5 : DARK_PURPLE
# &4 : DARK_RED
# &6 : GOLD
# &7 : GRAY
# &a : GREEN
# &o : ITALIC
# &d : LIGHT_PURPLE
# &k : MAGIC
# &c : RED
# &r : RESET
# &m : STRIKETHROUGH
# &n : UNDERLINE
# &f : WHITE
# &e : YELLOW

titles:
   home: "Shop Menu"
   list_players: "All Player Shops"
   settings: "Your Settings"
   commands: "Commands"

icons:
   menubar:
      back:
         type: "166"
         name: "Back"
         lore:
            - "&7Go back to previous window."
      search:
         type: "345"
         name: "Search"
         lore:
            - "&7Search for a specific player or item."
      last_page:
         type: "160:14"
         name: "Previous Page"
         lore:
            - "&7Go back."
      next_page:
         type: "160:14"
         name: "Next Page"
         lore:
            - "&7Go forward."
   home:
      list_own_shops:
         type: "54"
         name: "Your Shops"
         lore:
            - "&7List all shops"
            - "&7you own on the server."
      list_players:
         type: "397:3"
         name: "Player Shops"
         lore:
            - "&7List all players"
            - "&7with shops on the server."
      settings:
         type: "286"
         name: "Settings"
         lore:
            - "&7Change your shop"
            - "&7notification settings."
      commands:
         type: "116"
         name: "Commands"
         lore:
            - "&7Run commands available to operators."
   settings:
      notify_owner_on:
         type: "35:5"
         name: "Sales Notifications (owner)"
         lore:
            - "&7You will be notified"
            - "&7when players purchase from your shops."
      notify_owner_off:
         type: "35:14"
         name: "Sales Notifications (owner)"
         lore:
            - "&7You will not be notified"
            - "&7when players purchase from your shops."
      notify_user_on:
         type: "35:5"
         name: "Sales Notifications (user)"
         lore:
            - "&7You will be notified"
            - "&7when you make purchases from shops."
      notify_user_off:
         type: "35:14"
         name: "Sales Notifications (user)"
         lore:
            - "&7You will not be notified"
            - "&7when you make purchases from shops."
      notify_stock_on:
         type: "35:5"
         name: "Stock Notifications (owner)"
         lore:
            - "&7You will be notified"
            - "&7when your shops run out of stock or space."
      notify_stock_off:
         type: "35:14"
         name: "Stock Notifications (owner)"
         lore:
            - "&7You will not be notified"
            - "&7when your shops run out of stock or space."
   commands:
      currency:
         type: "388"
         name: "Check Server Currency"
         lore:
            - "&7Display what currency"
            - "&7the server is using."
      set_currency:
         type: "348"
         name: "Set Server Currency"
         lore:
            - "&7Set the server currency"
            - "&7to the item in your hand."
      set_gamble:
         name: "Set Gamble Display"
         lore:
            - "&7Set the gamble displays"
            - "&7to the item in your hand."
      refresh_displays:
         type: "352"
         name: "Refresh Shop Displays"
         lore:
            - "&7Refresh all of the"
            - "&7shop displays on the server."
      reload:
         type: "30"
         name: "Reload Plugin"
         lore:
            - "&7Reload the shop plugin."
   list:
      player_admin:
         type: "54"
         name: "Admin"
         lore:
            - "&7Shops owned by the server."