# THIS FILE IS USED TO CONFIGURE WHAT MESSAGES ARE DISPLAYED #
# ================================================================== #
# &b : AQUA
# &0 : BLACK
# &9 : BLUE
# &l : BOLD
# &3 : DARK_AQUA
# &1 : DARK_BLUE
# &8 : DARK_GRAY
# &2 : DARK_GREEN
# &5 : DARK_PURPLE
# &4 : DARK_RED
# &6 : GOLD
# &7 : GRAY
# &a : GREEN
# &o : ITALIC
# &d : LIGHT_PURPLE
# &k : MAGIC
# &c : RED
# &r : RESET
# &m : STRIKETHROUGH
# &n : UNDERLINE
# &f : WHITE
# &e : YELLOW

# [item] : The name of the item in the transaction #
# [item amount] : The amount of the item #
# [barter item] : The name of the barter item in the transaction #
# [barter item amount] : The amount of the barter item #
# [price] : The price of the items (adjusted to match virtual or physical currency) #
# [user] : The name of the player who used the shop #
# [owner] : The name of the shop owner #
# [server name] : The name of the server #
# [shop type] : The type of the shop (sell, buy, barter) #

transaction:
   SELL:
      user: '&7You bought &f[item amount] [item](s) &7from [owner] for &a[price]&7.'
      owner: '&7[user] bought &f[item amount] [item](s) &7from you for &a[price]&7.'
   BUY:
      user: '&7You sold &f[item amount] [item](s) &7to [owner] for &a[price]&7.'
      owner: '&7[user] sold &f[item amount] [item](s) &7to you for &a[price]&7.'
   BARTER:
      user: '&7You bartered &f[barter item amount] &7of your &f[barter item](s) &7for &f[item amount] &7of [owner]s &f[item](s)&7.'
      owner: '&7[user] bartered &f[item amount] &7of their &f[item](s) &7for &f[barter item amount] &7of your &f[barter item](s)&7.'

transaction_issue:
   SELL:
      shopNoStock: '&cThis shop is out of stock.'
      shopNoSpace: '&cThis shop does not have enough space in its inventory to accept your payment.'
      playerNoStock: '&cYou do not have sufficient funds to buy from this shop.'
      playerNoSpace: '&cYou do not have enough space in your inventory to buy from this shop.'
   BUY:
      shopNoStock: '&cThis shop is out of funds.'
      shopNoSpace: '&cThis shop does not have enough space in its inventory for your items.'
      playerNoStock: '&cYou do not have enough items to sell to this shop.'
      playerNoSpace: '&cYou do not have enough space in your inventory to accept the payment from this shop.'
   BARTER:
      shopNoStock: '&cThis shop is out of stock.'
      shopNoSpace: '&cThis shop does not have enough space in its inventory to barter with you.'
      playerNoStock: '&cYou do not have sufficient items to barter with this shop.'
      playerNoSpace: '&cYou do not have enough space in your inventory to barter with this shop.'

interaction:
   SELL:
      create: '&eYou have created a shop that sells &6[item](s)&e.'
      destroy: '&7You have destroyed your selling shop.'
      opDestroy: '&7You have destroyed a selling shop owned by [owner].'
      opOpen: '&7You are opening a selling shop owned by [owner].'
   BUY:
      create: '&eYou have created a shop that buys &6[item](s)&e.'
      destroy: '&7You have destroyed your buying shop.'
      opDestroy: '&7You have destroyed a buying shop owned by [owner].'
      opOpen: '&7You are opening a buying shop owned by [owner].'
   BARTER:
      create: '&eYou have created a shop that barters &6[item](s) &efor &6[barter item](s)&e.'
      destroy: '&7You have destroyed your bartering shop.'
      opDestroy: '&7You have destroyed a bartering shop owned by [owner].'
      opOpen: '&7You are opening a bartering shop owned by [owner].'

interaction_issue:
   createLine2: '&cThe amount (line 2) needs to be a positive number.'
   createLine3: '&cThe price (line 3) needs to be a positive number.'
   createNoItem: '&cYou must be holding the item you want to [shop type]'
   createDirection: '&cThe sign must be in front of the chest in order to create a shop.'
   createSameItem: '&cYou cannot create a barter shop where both items are the same.'
   createDisplayRoom: '&cThis shop could not created because there is no room for a display item.'
   createInsufficientFunds: '&cYou do not have the funds required to create this shop.'
   destroyInsufficientFunds: '&cYou do not have the funds required to destroy this shop.'
   initializeOtherShop: '&cYou may not initialize another players shop with an item.'
   destroyChest: '&cYou must remove the sign from this shop to break it.'
   useOwnShop: '&7You cannot use your own shop.'
   adminOpen: '&7Admin shops are not able to be opened.'

permission:
   use: '&cYou are not authorized to use [shop type]ing shops.'
   create: '&cYou are not authorized to create [shop type]ing shops.'
   destroy: '&cYou are not authorized to destroy shops.'
   buildLimit: '&cYou have already reached your build limit of [build limit] shops.'