# Thanks for downloading Shop! #
#==============================#

usePermissions: false

# If you want to use virtual money, install the plugin Vault and set this to true #
# Otherwise, shops will use physical items as the economy on the server #
useVault: false


# These allow you to charge money to players for creating/destroying their shops #
creationCost: 0
destructionCost: 0


# THIS SECTION IS ONLY USED IF VAULT IS BEING USED ON THE SERVER #
# ================================================================== #

# This will be the symbol in front of your currency on shop signs #
# For example, if your server is using 'cents' you would use the cents symbol #
vaultCurrencySymbol: $
# ================================================================== #



# THIS SECTION IS ONLY USED IF VAULT IS NOT BEING USED ON THE SERVER #
# ================================================================== #

# For item IDs, use this website:  http://minecraft-ids.grahamedgecombe.com  #
# For example, if you wanted to use Lapis Lazuli as your currency, put 351;4    #
# Default is set to Emerald (388;0) #
itemCurrencyID: 388;0

# This is what your currency will be called on shop signs #
# This should match the name of the item you are using for the section above #
itemCurrencyName: Emerald(s)
# ================================================================== #