name: Shop
author: Tanner Embry (SnowGears)
description: Easily create shops to buy or sell items!
version: 1.5.3.8
main: com.snowgears.shop.Shop
softdepend: [Vault]
permissions:
    shop.use:
        description: Allows player to use all shops.
        default: op
    shop.use.selling:
        description: Allows player to use selling shops.
        default: op
    shop.use.buying:
        description: Allows player to use buying shops.
        default: op
    shop.use.barter:
        description: Allows player to use barter shops.
        default: op
    shop.create:
        description: Allows player to create all shops.
        default: op
    shop.create.selling:
        description: Allows player to create selling shops.
        default: op
    shop.create.buying:
        description: Allows player to create buying shops.
        default: op
    shop.create.barter:
        description: Allows player to create barter shops.
        default: op
    shop.destroy:
        description: Allows player to destroy their own shops.
        default: op
    shop.buildlimit.#:
         description: Restricts the number of shop a player can build to #.
         default: op
    shop.operator:
        description: Allows access to operator actions.
        default: op
commands:
   shop:
      description: Different commands pertaining to plugin
      usage: /<command>
   chestshop:
      description: Different commands pertaining to plugin
      usage: /<command>